name: 📚 Documentation Improvement
description: Suggest improvements to documentation, examples, or guides
title: "[Docs]: "
labels: ["documentation", "good first issue", "hacktoberfest"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! 📚
        
        Great documentation makes Logixia more accessible to everyone.
        This is often a perfect first contribution!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - README.md
        - API Documentation
        - Getting Started Guide
        - Examples
        - Code Comments
        - Contributing Guide
        - Tutorials
        - FAQ
        - Other
    validations:
      required: true

  - type: textarea
    id: current-issue
    attributes:
      label: Current Issue
      description: What's wrong with the current documentation?
      placeholder: |
        Describe what's unclear, missing, outdated, or incorrect in the 
        current documentation.
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: |
        Describe your suggested improvements. Be specific about:
        - What should be added, changed, or removed
        - How it should be organized
        - What examples would be helpful
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is this documentation located?
      placeholder: |
        - File path: (e.g., README.md, docs/api.md)
        - Section: (e.g., "Getting Started", "API Reference")
        - Line numbers: (if applicable)
        - URL: (if it's online documentation)
    validations:
      required: false

  - type: textarea
    id: target-audience
    attributes:
      label: Target Audience
      description: Who would benefit from this improvement?
      placeholder: |
        - New users getting started
        - Experienced developers
        - Contributors
        - Specific use case developers
        - Everyone
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Example Content (Optional)
      description: If you have ideas for specific content, share them here
      render: markdown
      placeholder: |
        ```typescript
        // Example code that should be documented
        ```
        
        Or write example documentation text here...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this documentation improvement?
      options:
        - Low - Minor improvement
        - Medium - Helpful for users
        - High - Important for usability
        - Critical - Blocking user adoption
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about this documentation improvement
      placeholder: |
        - Links to related issues or discussions
        - Screenshots of confusing parts
        - Examples from other projects
        - User feedback you've received
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues for similar documentation requests
          required: true
        - label: I have identified the specific location that needs improvement
          required: false
        - label: I would be willing to help write or improve this documentation
          required: false
        - label: I have considered the target audience for this documentation
          required: true