name: ✨ Feature Request
description: Suggest a new feature or enhancement for Logixia
title: "[Feature]: "
labels: ["enhancement", "needs-discussion"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! ✨
        
        Before submitting, please:
        - Search existing issues to avoid duplicates
        - Consider if this fits with Logixia's goals
        - Think about implementation complexity

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see
      placeholder: Briefly describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is.
        Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        A clear and concise description of what you want to happen.
        Include any specific API design ideas or implementation details.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Alternative solutions or features you've considered
      placeholder: |
        A clear and concise description of any alternative solutions 
        or features you've considered.
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. As a developer, I want to...
        2. When building applications that...
        3. This would help with...
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: API Design (Optional)
      description: If you have ideas about the API design, share them here
      render: typescript
      placeholder: |
        // Example API usage
        const logger = new Logixia({
          // new feature configuration
        });
        
        logger.newFeature({
          // usage example
        });
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my adoption
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Implementation Complexity (Your Estimate)
      description: How complex do you think this feature would be to implement?
      options:
        - Low - Simple addition
        - Medium - Moderate changes required
        - High - Significant implementation effort
        - Unknown - Not sure
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples
      placeholder: |
        Add any other context, screenshots, mockups, or examples about 
        the feature request here.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues for similar feature requests
          required: true
        - label: This feature aligns with Logixia's goals and scope
          required: true
        - label: I would be willing to help implement this feature
          required: false
        - label: I have provided clear use cases for this feature
          required: true